name: Client Push CI

on:
  push:
    paths:
      - '.github/workflows/client_push.yml'
      - 'wr_client/**'
  pull_request:
    paths:
      - '.github/workflows/client_push.yml'
      - 'wr_client/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker - Login
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin

    - name: Docker - Build (with tag)
      run: |
           docker build \
           --build-arg SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} \
           --tag docker.pkg.github.com/shiryel/videochat_p2p/wr_client:latest \
           wr_client
    - name: Docker - Push
      run: docker push docker.pkg.github.com/shiryel/videochat_p2p/wr_client:latest

    - name: AWS - Set PEM
      run: |
        echo "${{ secrets.AWS_PEM }}" > temp.pem
        chmod 400 temp.pem
    
    - name: AWS - Set Docker Login
      run: |
           ssh -q -o "StrictHostKeyChecking no" -i temp.pem ${{ secrets.AWS_SSH }} \
             "echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin"
    - name: AWS - Exclude last container if exists
      run: |
           ssh -q -o "StrictHostKeyChecking no" -i temp.pem ${{ secrets.AWS_SSH }} \
             docker rm -f webrtc_client
    - name: AWS - Get and run new Image
      if: success() || failure()
      run: |
        ssh -o "StrictHostKeyChecking no" -i temp.pem ${{ secrets.AWS_SSH }} \
          docker pull docker.pkg.github.com/shiryel/videochat_p2p/wr_client:latest
        ssh -o "StrictHostKeyChecking no" -i temp.pem ${{ secrets.AWS_SSH }} \
          docker run -d \
            --name webrtc_client \
            --hostname webrtc_client \
            --publish 5001:80 \
            --restart=always \
            docker.pkg.github.com/shiryel/videochat_p2p/wr_client:latest
    - name: AWS - Clear Docker Login
      if: always()
      run: |
           ssh -q -o "StrictHostKeyChecking no" -i temp.pem ${{ secrets.AWS_SSH }} \
             docker logout docker.pkg.github.com
    - name: AWS - Clear PEM
      if: always()
      run: rm -f temp.pem
