name: Server Test CI

on:
  push:
    paths:
      - '.github/**'
      - 'wr_server/**'
  pull_request:
    paths:
      - '.github/**'
      - 'wr_server/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.3 # Define the elixir version [required]
        otp-version: 22.2 # Define the OTP version [required]
    - name: Get deps, and Run tests
      run: |
           cd wr_server/
           mix deps.get
           mix test
